exp_name: 'pdb_trial_2'
actnorm: True
aggregation_method: 'sum'
attention: True
augment_noise: 0
batch_size: 2
break_train_epoch: False
brute_force: False
clip_grad: True
condition_time: True
conditioning: []
context_node_nf: 0
data_augmentation: False
datadir: 'data/pdb_files'
dataset: 'pdb'
dequantization: 'argmax_variational'
diffusion_loss_type: 'l2'
diffusion_noise_precision: 1e-5
diffusion_noise_schedule: 'polynomial_2'
diffusion_steps: 200
dp: True
ema_decay: 0
filter_n_atoms: null
generate_epochs: 1
include_charges: False
inv_sublayers: 1
lr: 2e-4
model: 'egnn_dynamics'
n_epochs: 4
n_layers: 2
n_report_steps: 1
n_stability_samples: 500
nf: 64
no_cuda: false
no_wandb: false
normalize_factors: [1, 4, 1]
normalization_factor: 1
norm_constant: 1
num_workers: 0
ode_regularization: 1e-3
online: false
probabilistic_model: 'diffusion'
remove_h: false
resume: null
save_model: True
sin_embedding: False
start_epoch: 0
tanh: True
test_epochs: 2
trace: 'hutch'
visualize_every_batch: 1e8
wandb_usr: jerhanwl
