exp_name: 'debug_10'
actnorm: True
aggregation_method: 'sum'
attention: True
augment_noise: 0
batch_size: 128
break_train_epoch: False
brute_force: False
clip_grad: True
condition_time: True
conditioning: []
data_augmentation: False
datadir: 'qm9/temp'
dataset: 'qm9'
dequantization: 'argmax_variational'
diffusion_loss_type: 'l2'
diffusion_noise_precision: 1e-5
diffusion_noise_schedule: 'polynomial_2'
diffusion_steps: 500
dp: True
ema_decay: 0.999
filter_n_atoms: null
generate_epochs: 1
include_charges: True
inv_sublayers: 1
lr: 2e-4
model: 'egnn_dynamics'
n_epochs: 200
n_layers: 6
n_report_steps: 1
n_stability_samples: 500
nf: 128
no_cuda: false
no_wandb: false
normalize_factors: [1, 4, 1]
normalization_factor: 1
num_workers: 0
ode_regularization: 1e-3
online: true
probabilistic_model: 'diffusion'
remove_h: false
resume: null
save_model: True
sin_embedding: False
start_epoch: 0
tanh: True
test_epochs: 10
trace: 'hutch'
visualize_every_batch: 1e8
wandb_usr: null
